### ISSUE TITLE
NAtive HA not available

### ISSUE THREAD

**Issue by lavalex** [ibm-messaging/mq-helm#89] opened 2024-06-24 06:49 UTC
Hello,

I'm trying to deploy MQ Advanced container 9.3.0.17-r3 using this chart and I getting this error:

2024-06-24T06:29:31.552Z Using queue manager name: QMPRD1
2024-06-24T06:29:31.552Z CPU architecture: amd64
2024-06-24T06:29:31.552Z Linux kernel version: 5.14.0-284.43.1.el9_2.x86_64
2024-06-24T06:29:31.552Z Container runtime: not-found
2024-06-24T06:29:31.552Z Base image: Red Hat Enterprise Linux 8.10 (Ootpa)
2024-06-24T06:29:31.552Z Running as user ID 1000 with primary group 0, and supplementary groups 0,1000,65534
2024-06-24T06:29:31.552Z Capabilities: none
2024-06-24T06:29:31.552Z seccomp enforcing mode: disabled
2024-06-24T06:29:31.552Z Process security attributes: system_u:system_r:container_t:s0:c9,c27
2024-06-24T06:29:31.552Z Detected 'nfs4' volume mounted to /mnt/mqm
2024-06-24T06:29:31.584Z Created directory structure under /var/mqm
2024-06-24T06:29:31.584Z Image created: 2024-05-30T13:49:30+00:00
2024-06-24T06:29:31.584Z Image tag: ibm-mqadvanced-server:9.3.0.17-r3.20240530134031.e3ab0fd-amd64
2024-06-24T06:29:31.609Z MQ version: 9.3.0.17
2024-06-24T06:29:31.609Z MQ level: p930-017-240404
2024-06-24T06:29:31.609Z MQ license: Production
2024-06-24T06:29:31.953Z Starting web server
2024-06-24T06:29:31.954Z Creating queue manager QMPRD1
2024-06-24T06:29:32.003Z Error 93 creating queue manager: AMQ5708E: Native HA is unavailable.

2024-06-24T06:29:32.003Z /opt/mqm/bin/crtmqm: exit status 93

When I try to deploy MQ Developer image, it works fine. What am I missing? I tried to change annotations, but I think they have no effect on the container itself, may be only on the licensing operator, that I also tried to deploy. 

I found a similar thread here, but I am not sure I understood how to proceed. Any help will be very welcome, thanks!

**Comment by callumpjackson** [comment] 2024-06-24 10:13
Hi - I think this issue is a duplicate of [issue 51](https://github.com/ibm-messaging/mq-helm/issues/51). Closing at the moment, but feel free to re-open if needed.

**Closed by callumpjackson** 2024-06-24 10:13 UTC
